ServerEvents.recipes(event => {
    event.remove({ id: 'thermal:machines/press/press_iron_ingot_to_gear' })
    event.remove({ id: 'thermal:machines/press/press_gold_ingot_to_gear' })
    event.remove({ id: 'thermal:parts/iron_gear' })
    event.remove({ id: 'thermal:parts/gold_gear' })
    event.remove({ id: 'thermal:parts/copper_gear' })
    event.remove({ id: 'thermal:parts/diamond_gear' })
    event.remove({ id: 'thermal:parts/emerald_gear' })
    event.remove({ id: 'thermal:parts/netherite_gear' })
    event.remove({ id: 'thermal:parts/quartz_gear' })
    event.remove({ id: 'thermal:parts/ruby_gear' })
    event.remove({ id: 'thermal:parts/sapphire_gear' })
    event.remove({ id: 'thermal:parts/tin_gear' })
    event.remove({ id: 'thermal:parts/lead_gear' })
    event.remove({ id: 'thermal:parts/silver_gear' })
    event.remove({ id: 'thermal:parts/nickel_gear' })
    event.remove({ id: 'thermal:parts/signaum_gear' })
    event.remove({ id: 'thermal:parts/lumium_gear' })
    event.remove({ id: 'thermal:parts/enderim_gear' })
    event.remove({ id: 'thermal:parts/bronze_gear' })
    event.remove({ id: 'thermal:parts/electrum_gear' })
    event.remove({ id: 'thermal:parts/invar_gear' })
    event.remove({ id: 'thermal:parts/constantan_gear' })
    event.remove({ id: 'industrialforegoing:iron_gear' })
    event.remove({ id: 'industrialforegoing:gold_gear' })
    event.remove({ id: 'industrialforegoing:diamond_gear' })
    event.replaceInput({ output: '#forge:gears' }, 'minecraft:iron_nugget', 'industrialforegoing:plastic')
})