Platform.getInfo('kubejs').name = 'Tamamo The Tweaks'
StartupEvents.registry('block', e => {
    e.create('tamamo_the_tweaks:raw_netherite_scrap_block').displayName('下界合金碎片块').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_diamond_tool")

    e.create('tamamo_the_tweaks:dust_block_1x').displayName('尘土1x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:dust_block_2x').displayName('尘土2x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")

    e.create('tamamo_the_tweaks:crushed_netherrack_block_1x').displayName('粉碎下界岩1x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_netherrack_block_2x').displayName('粉碎下界岩2x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_netherrack_block_3x').displayName('粉碎下界岩3x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_netherrack_block_4x').displayName('粉碎下界岩4x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_netherrack_block_5x').displayName('粉碎下界岩5x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_netherrack_block_6x').displayName('粉碎下界岩6x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_netherrack_block_7x').displayName('粉碎下界岩7x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_netherrack_block_8x').displayName('粉碎下界岩8x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_netherrack_block_9x').displayName('粉碎下界岩9x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")

    e.create('tamamo_the_tweaks:crushed_blackstone_block_1x').displayName('粉碎黑石1x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_blackstone_block_2x').displayName('粉碎黑石2x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_blackstone_block_3x').displayName('粉碎黑石3x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_blackstone_block_4x').displayName('粉碎黑石4x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_blackstone_block_5x').displayName('粉碎黑石5x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_blackstone_block_6x').displayName('粉碎黑石6x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_blackstone_block_7x').displayName('粉碎黑石7x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_blackstone_block_8x').displayName('粉碎黑石8x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_blackstone_block_9x').displayName('粉碎黑石9x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")

    e.create('tamamo_the_tweaks:crushed_basalt_block_1x').displayName('粉碎玄武岩1x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_basalt_block_2x').displayName('粉碎玄武岩2x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_basalt_block_3x').displayName('粉碎玄武岩3x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_basalt_block_4x').displayName('粉碎玄武岩4x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_basalt_block_5x').displayName('粉碎玄武岩5x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_basalt_block_6x').displayName('粉碎玄武岩6x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_basalt_block_7x').displayName('粉碎玄武岩7x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_basalt_block_8x').displayName('粉碎玄武岩8x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_basalt_block_9x').displayName('粉碎玄武岩9x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")

    e.create('tamamo_the_tweaks:crushed_end_stone_block_1x').displayName('粉碎末地石1x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_end_stone_block_2x').displayName('粉碎末地石2x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_end_stone_block_3x').displayName('粉碎末地石3x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_end_stone_block_4x').displayName('粉碎末地石4x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_end_stone_block_5x').displayName('粉碎末地石5x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_end_stone_block_6x').displayName('粉碎末地石6x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_end_stone_block_7x').displayName('粉碎末地石7x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_end_stone_block_8x').displayName('粉碎末地石8x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('tamamo_the_tweaks:crushed_end_stone_block_9x').displayName('粉碎末地石9x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")

    e.create('tamamo_the_tweaks:blaze_rod_block').displayName('烈焰棒块').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
    e.create('allthecompressed:blaze_rod_block_1x').displayName('烈焰棒块1x').requiresTool(true).tagBlock("mineable/pickaxe").tagBlock("minecraft:needs_iron_tool")
})