StartupEvents.registry('fluid', e => {
    e.create('echo_essence')
        .thickTexture(0x03404F)
        .bucketColor(0x03404F)
        .displayName('回响精华')

    e.create('molten_steel')
        .thickTexture(0x232323)
        .bucketColor(0x232323)
        .displayName('熔融钢')

    e.create('cryotheum')
        .bucketColor(0x23F7FB)
        .stillTexture('kubejs:block/cryotheum_still')
        .flowingTexture('kubejs:block/cryotheum_flow')
        .displayName('极寒之凛冰')
        .temperature(-1200)
    e.create('pyrotheum')
        .bucketColor(0xFFC325)
        .stillTexture('kubejs:block/pyrotheum_still')
        .flowingTexture('kubejs:block/pyrotheum_flow')
        .displayName('烈焰之炽焱')
        .temperature(40000)
})
