ServerEvents.recipes(event => {
    event.replaceInput({ output: 'compactmachines:machine_tiny' }, 'minecraft:copper_block', 'tamamo_the_tweaks:compressed_core')
    event.replaceInput({ output: 'compactmachines:machine_small' }, 'minecraft:iron_block', 'tamamo_the_tweaks:compressed_core')
    event.replaceInput({ output: 'compactmachines:machine_normal' }, 'minecraft:gold_block', 'tamamo_the_tweaks:compressed_core')
    event.replaceInput({ output: 'compactmachines:machine_large' }, 'minecraft:obsidian', 'tamamo_the_tweaks:compressed_core')
    event.replaceInput({ output: 'compactmachines:machine_giant' }, 'minecraft:diamond_block', 'tamamo_the_tweaks:compressed_core')
    event.replaceInput({ output: 'compactmachines:machine_maximum' }, 'minecraft:netherite_block', 'tamamo_the_tweaks:compressed_core')
    event.replaceInput({ output: 'compactmachines:machine_tiny' }, 'compactmachines:wall', 'minecraft:copper_block')
    event.replaceInput({ output: 'compactmachines:machine_small' }, 'compactmachines:wall', 'minecraft:iron_block')
    event.replaceInput({ output: 'compactmachines:machine_normal' }, 'compactmachines:wall', 'minecraft:gold_block')
    event.replaceInput({ output: 'compactmachines:machine_large' }, 'compactmachines:wall', 'minecraft:obsidian')
    event.replaceInput({ output: 'compactmachines:machine_giant' }, 'compactmachines:wall', 'minecraft:diamond_block')
    event.replaceInput({ output: 'compactmachines:machine_maximum' }, 'compactmachines:wall', 'minecraft:netherite_block')
})
